### ISSUE TITLE
Not able to show tooltip for treemap and getting  Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by kailashkumarp** [kurkle/chartjs-chart-treemap#235]
Hi All,

I am not able to show tooltip with chartjs-chart-treemap , getting below errors on mouse over

 TypeError: Cannot read properties of undefined (reading 'call')
    at gn._positionChanged (255.1e5936cb97f942ec.js:1:175779)
    at gn.handleEvent (255.1e5936cb97f942ec.js:1:175366)
    at Object.afterEvent (255.1e5936cb97f942ec.js:1:176414)
    at q (255.1e5936cb97f942ec.js:1:1670)
    at fc._notify (255.1e5936cb97f942ec.js:1:109400)
    at fc.notify (255.1e5936cb97f942ec.js:1:109221)
    at Bt.notifyPlugins (255.1e5936cb97f942ec.js:1:127824)
    at Bt._eventHandler (255.1e5936cb97f942ec.js:1:128475)
    at s (255.1e5936cb97f942ec.js:1:126367)
    at Bt.<anonymous> (255.1e5936cb97f942ec.js:1:83524)

Thanks,
Kailash

**Comment by elyak123** [comment]
I just resolved this issue. The most likely reason for this is that you might not be performing the registration properly, doing it twice or doing it in the wrong place. I hope this helps for anyone else here.
